- project:
    templates:
      - check-requirements
      - openstack-cover-jobs
      - openstack-python3-ussuri-jobs
      - publish-openstack-docs-pti
    check:
      jobs:
        - ironic-lib-bios-ipmi-direct-tinyipa-src
        - ironic-lib-bios-ipmi-iscsi-tinyipa-src
    gate:
      jobs:
        - ironic-lib-bios-ipmi-direct-tinyipa-src
        - ironic-lib-bios-ipmi-iscsi-tinyipa-src
    post:
      jobs:
        - ironic-python-agent-build-image-tinyipa
