- project:
    templates:
      - check-requirements
      - openstack-cover-jobs
      - openstack-python3-zed-jobs
      - publish-openstack-docs-pti
    check:
      jobs:
        - ironic-lib-local-uefi-ipmi-src
        - ironic-lib-netboot-bios-ipmi-src
    gate:
      queue: ironic
      jobs:
        - ironic-lib-local-uefi-ipmi-src
        - ironic-lib-netboot-bios-ipmi-src
    post:
      jobs:
        - ironic-python-agent-build-image-tinyipa
