- project:
    templates:
      - check-requirements
      - openstack-cover-jobs
      - openstack-lower-constraints-master-branch-jobs
      - openstack-python3-yoga-jobs
      - publish-openstack-docs-pti
    check:
      jobs:
        - ironic-lib-wholedisk-bios-ipmi-src
        - ironic-lib-partition-bios-ipmi-src
    gate:
      jobs:
        - ironic-lib-wholedisk-bios-ipmi-src
        - ironic-lib-partition-bios-ipmi-src
    post:
      jobs:
        - ironic-python-agent-build-image-tinyipa
