- project:
    templates:
      - check-requirements
      - openstack-cover-jobs
      - openstack-python-jobs
      - openstack-python3-train-jobs
      - publish-openstack-docs-pti
    check:
      jobs:
        - ironic-lib-wholedisk-bios-ipmi-direct-tinyipa-src
        - ironic-lib-partition-bios-ipmi-direct-tinyipa-src
    gate:
      jobs:
        - ironic-lib-wholedisk-bios-ipmi-direct-tinyipa-src
        - ironic-lib-partition-bios-ipmi-direct-tinyipa-src
